# Tracker config

actor: '/netscratch/jeetmal/videos/Ameer/videos/Ameer_mtracker_6'
save_folder: '/netscratch/jeetmal/output/metrical-tracker/Ameer/6_new/'
optimize_shape: true
optimize_jaw: true
optimize_neck: false
undistort: true
camera_id: 6
begin_frames: 1
keyframes: [ 2, 3 ]