FREIHAND-VAL:
    TYPE: ImageDataset
    DATASET_FILE: hamer_evaluation_data/freihand_val.npz
    IMG_DIR: /home/user/datasets/FreiHAND_pub_v2_eval/evaluation/rgb/
    KEYPOINT_LIST: [0] # Dummy

HO3D-VAL:
    TYPE: ImageDataset
    DATASET_FILE: hamer_evaluation_data/ho3d_val.npz
    IMG_DIR: /home/user/datasets/HO3D_v2/evaluation/
    KEYPOINT_LIST: [0] # Dummy

EGO4D-TEST-ALL:
    TYPE: ImageDataset
    DATASET_FILE: hamer_evaluation_data/TEST_ego4d_img_all.npz
    IMG_DIR: /home/user/datasets/HInt_annotation_partial/TEST_ego4d_img/
    KEYPOINT_LIST: [0] # Dummy

EGO4D-TEST-VIS:
    TYPE: ImageDataset
    DATASET_FILE: hamer_evaluation_data/TEST_ego4d_img_vis.npz
    IMG_DIR: /home/user/datasets/HInt_annotation_partial/TEST_ego4d_img/
    KEYPOINT_LIST: [0] # Dummy

EGO4D-TEST-OCC:
    TYPE: ImageDataset
    DATASET_FILE: hamer_evaluation_data/TEST_ego4d_img_occ.npz
    IMG_DIR: /home/user/datasets/HInt_annotation_partial/TEST_ego4d_img/
    KEYPOINT_LIST: [0] # Dummy

EPICK-TEST-ALL:
    TYPE: ImageDataset
    DATASET_FILE: hamer_evaluation_data/TEST_epick_img_all.npz
    IMG_DIR: /home/user/datasets/HInt_annotation_partial/TEST_epick_img/
    KEYPOINT_LIST: [0] # Dummy

EPICK-TEST-VIS:
    TYPE: ImageDataset
    DATASET_FILE: hamer_evaluation_data/TEST_epick_img_vis.npz
    IMG_DIR: /home/user/datasets/HInt_annotation_partial/TEST_epick_img/
    KEYPOINT_LIST: [0] # Dummy

EPICK-TEST-OCC:
    TYPE: ImageDataset
    DATASET_FILE: hamer_evaluation_data/TEST_epick_img_occ.npz
    IMG_DIR: /home/user/datasets/HInt_annotation_partial/TEST_epick_img/
    KEYPOINT_LIST: [0] # Dummy

NEWDAYS-TEST-ALL:
    TYPE: ImageDataset
    DATASET_FILE: hamer_evaluation_data/TEST_newdays_img_all.npz
    IMG_DIR: /home/user/datasets/HInt_annotation_partial/TEST_newdays_img/
    KEYPOINT_LIST: [0] # Dummy

NEWDAYS-TEST-VIS:
    TYPE: ImageDataset
    DATASET_FILE: hamer_evaluation_data/TEST_newdays_img_vis.npz
    IMG_DIR: /home/user/datasets/HInt_annotation_partial/TEST_newdays_img/
    KEYPOINT_LIST: [0] # Dummy

NEWDAYS-TEST-OCC:
    TYPE: ImageDataset
    DATASET_FILE: hamer_evaluation_data/TEST_newdays_img_occ.npz
    IMG_DIR: /home/user/datasets/HInt_annotation_partial/TEST_newdays_img/
    KEYPOINT_LIST: [0] # Dummy
